### ISSUE TITLE
Package with openff-toolkit base

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-qcsubmit#100]
It would be good to shrink down the package a little by using openff-toolkit-base and rdkit which would get users the majority of the functionality from qcsubmit the other option dependencies would be fragmenter and openeye. The components that need these should then fail with messages on how to install them.

**Comment by dotsdl** [comment]
@jthorton would you like me to take a stab at this? I think this and `openff-evaluator` are the last of the `openff-*` packages that need to switch to `openff.toolkit` usage internally. 

Is there anything blocking such a move, such as your bespoke work or the partner benchmark?

**Comment by dotsdl** [comment]
@j-wags and @SimonBoothroyd pinging from discussion.

**Comment by jthorton** [comment]
yeah, I am holding back from the change until I can confirm it won't complicate the bespoke work as I am still making changes and will still work with fragmenter. Some things I need to check/change
- fragmenter/openeye=2019.10.2 works with `openff-toolkit`
- update bespokefit to use `openff-toolkit` once the new forcebalance conda package is out

**Comment by dotsdl** [comment]
Ah, understood, thanks @jthorton!

Blockers are:
- fragmenter refactor
- forcebalance conda package

We discussed this today in the coredevs call. I'm sorry fragmenter in particular is blocking here. I believe we have work on that allocated in the next few months as it's been a pain point for us for a while.

**Comment by jthorton** [comment]
It looks like openff-toolkit, fragmenter=0.0.7 and openeye-toolkits=2019.10.2 are working together in tests so I have updated to the `openff-toolkit` package on master.

**Comment by jthorton** [comment]
closed in #102
