### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/openff-qcsubmit#190]
If there is anything blocking a new release of `openff-qcsubmit`, can we link those issues/PRs here? Otherwise happy to take a swing at cutting a release if we have instructions for it.

**Comment by jthorton** [comment]
Nothing blocking from my side, the release history however does need updating just noticed it has been missed for the last few releases. I can update it and cut a release if you like?

**Comment by dotsdl** [comment]
Ah yes, that'd be great! Thank you! Will allow us to deploy on `qca-dataset-submission` for the fat pubchem sets. :grin:

**Comment by jthorton** [comment]
Done (finally 🎉 )!
