### ISSUE TITLE
Deduplication inchi check vs aromaticity

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-qcsubmit#255]
The deduplication check hashes molecules via inchikey, then tries to remap them via an isomorphism check. Unfortunately structures like the below have the same inchikey, but different bond orders/aromaticity perception, so this raises an assertion error here: https://github.com/openforcefield/openff-qcsubmit/blob/2fa465a87ffea4c5b02d5d0cd8622d1a22d4fe83/openff/qcsubmit/workflow_components/utils.py#L713-L723

In this particular case, adding `aromatic_matching=False` to the `are_isomorphic` check did fix it for me.

<img width="269" alt="Screenshot 2024-01-30 at 8 51 13 pm" src="https://github.com/openforcefield/openff-qcsubmit/assets/31115101/1ce0a966-994b-48eb-ab27-ee27ce301792">
<img width="283" alt="Screenshot 2024-01-30 at 8 51 16 pm" src="https://github.com/openforcefield/openff-qcsubmit/assets/31115101/07c89a0a-7054-43e0-8a37-0d5157f0a27d">

**Comment by jthorton** [comment]
Ah another one for the ever-growing list of deduplication edge cases which is where the formal charge and bond order matching settings come from. I think your solution should be fine generally as this check is only ran if the inchi matches!
