### ISSUE TITLE
meta.yaml missing

### ISSUE THREAD

**Issue by spamidig** [openforcefield/openff-qcsubmit#271]
devtools/conda-env/meta.yaml mentioned in the installation  is missing from distribution. Can this be updated.

**Comment by j-wags** [comment]
Thanks for the report, I've opened a PR to fix this. It'll change the docs to recommend using `devtools/conda-envs/basic.yaml`.

**Comment by j-wags** [comment]
I've updated the docs, but the docs won't update until our next release. In the meantime, switching to use the yaml file I mentioned above should fix your issue. Please reopen this issue if that's not the case :-)
