### ISSUE TITLE
Component Private settings.

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-qcsubmit#42]
In the multiprocessing update by @trevorgokey we introduce new per component parameters that should be immutable by users, mainly this is a flag which determines if the component produces duplicates and if we should run deduplication on the output of the component. This flag should be set in the constructor and should be hidden from the user as we don't want them to change it by accident. My idea is to use introduce a private `_settings` parameter to the base component which takes the following immutable pydantic class which can easily be extended to capture more private settings. While the `_settings` object can still be changed at runtime the effort required is much higher as the user has to import the class make a new settings instance and then swap it out, this way we ensure it is intentional if someone does this rather than accidentally turning off the deduplication stage while trying to set a different parameter.  This way the settings are also not exported to json which means someone can not export a workflow to json and change the file before loading it back in.

Are there any possible downsides to this approach? 

```python
class Settings(BaseModel):
    process_parallel: bool = True
    produces_duplicates: bool = True

    class Config:
        allow_mutation: bool = False
         extra: "forbid"
```

**Comment by trevorgokey** [comment]
Yeah I think having a structure to keep the private bits separate would be good, especially if the idea is to omit them from serialization. We may opt to serialize a reference to a frozen set of settings, that can be pulled in/created automatically upon deserialization. I can see this being very useful for dataset versioning and keeping track of provenance for the workflows.

Would these be better served as calling them properties? Settings seems like data which should be user mutable. Properties seems like a more appropriate name in this context, and I think we can design them such that it is only possible to change the entire properties object, essentially making it a different component.

**Comment by jthorton** [comment]
Yeah very happy to change the name and I think the above can only be modified by swapping out the entire settings object note the config settings. Ill add this in after we get your PR in as I am planning a slight refactor and improvement of the workflow components by moving to a more factory-like setup so users can inject new components easier for development and testing.

**Comment by jthorton** [comment]
Now that pydantic supports private attributes update to use proper type hints for class vs private attributes.
