### ISSUE TITLE
Torsiondrive Factory Torsion Selection

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openff-qcsubmit#59]
While some modules like the Coverage filter and the SMARTS filter allow users to declare which types of torsions are allowed to be driven in torsiondrive datasets this is too specific for exploratory datasets where we wish to rotate all torsions. By default, this case is covered by the torsiondrive factory but it also selects trivial rotations like methyl groups. I think it would be best to add a setting to the factory to allow users to specify certain groups they do not wish to rotate this could be an enum of predefined types or groups of types or we could allow smarts patterns or both. 

This is not a problem when we use fragmenter to make a torsiondrive dataset as it excludes certain trivial terminal torsions.

**Comment by jthorton** [comment]
I think it might be best to have an extra argument in the torsiondrive factory which can take custom or predefined smarts patterns for certain groups we do not wish to be driven something like this

```python
from qcsubmit.factories import TorsiondriveDatasetFactory
from qcsubmit import FunctionalGroups as fg

factory = TorsiondriveDatasetFactory()

dataset = factory.create_dataset(ignore_torsions=[fg.Methyl, "my_smarts", ...])
```
The factory will then remove any entries from the dataset whose target torsion central bond matches with any of the supplied smarts patterns. If not an argument in the function this could be an attribute on the factory class maybe, this would also allow for the validation of the smarts before running the workflow, ie checking the number of tagged atoms is either 2 or 4.

**Comment by jchodera** [comment]
This sounds great!

Would the specified SMARTS be _tagged_ SMARTS delineating the torsion, such as `[*:1]~[*:2]-[CH3:3]-[H:4]` for a methyl torsion?

**Comment by jthorton** [comment]
Unfortunately, this still needs to be fixed but is now further complicated by the fact we want to support 2D scans involving any combination of two degrees of freedom. I think I am now moving to the idea of two new workflow components which can handle 1D and 2D scans respectively. These components should be able to handle multiple allowed smarts with their own distinct scan ranges I imagine something like this in the 1D case

```python
from openff.qcsubmit.workflow_components import ScanFilter1D

filter = ScanFilter1D()
# add a methyl full scan
filter.add_scan(smarts="[*:1]~[*:2]-[CH3:3]-[H:4]", range=(-165, 180))
# add a limited ring scan
filter.add_scan(smarts="[*:1]~[*:2]:[*:3]~[*:4]", range=(-40, 40)) 
# inspect the first scan
filter.scans[0]
``` 
> Scan1D(smarts="[*:1]~[*:2]-[CH3:3]-[H:4]", range=(-165, 180))

We could then have something similar for the 2D case. I am not sure if these components should also filter out unwanted scans? If the user has fragmented before this component the targeted bond has already been tagged by fragmenter would we want to allow this component to change the torsion driven or if it does not match those defined here should it be removed? or should the component simply tag the torsions it finds and that's it. If this is the case the torsiondrive factory would then need to filter out any molecules which do not have a tagged torsion and would no longer drive everything. 
tagging @SimonBoothroyd @trevorgokey as I know you have both hit this issue.

**Comment by SimonBoothroyd** [comment]
Thanks for thinking this through @jthorton!

I wonder if there are two categories of components that could be added - enumerators which enumerate and tag all of the torsions which match the given patterns to drive (I think the current workflow essentially already contains this implicitly where the scan to enumerate is defined by a SMARTS identifying a rotatable bond?), and then components which filter based on already identified scans.

This would allow writing something like:

```
from openff.qcsubmit.workflow_components import ScanEnumerator

enumerator = ScanEnumerator()

# Enumerate all 1D amide proper torsions
enumerator.add_torsion_scan(
    smarts="[C:1]-[NX3:2]-[CX3:3]=[O:4]",
    scan_range=(-180.0, 180.0),
    scan_increment=15
)
# Enumerate all 2D aryl amide proper torsions
enumerator.add_double_torsion_scan(
    smarts1="[C:1]-[NX3:2]-[CX3:3]=[O:4]",
    smarts2="[C:1]:[C:2]-[CX3:2](=O)-[NX3:4]",
    scan_range1=(-180.0, 180.0),
    scan_range2=(-180.0, 180.0),
    scan_increment=15
)
# Enumarte all amine impropers
enumerator.add_improper_scan(
    central_smarts="[NX3:1]",
    smarts="[N:1]([*:2])([*:3])([*:4])",
    scan_range=(-50, 50.0),
    scan_increment=4
)

```

where here I tried to match the interface of the `TorsionIndexer` class, and then also:

```
from openff.qcsubmit.workflow_components import ScanFilter

filter = ScanFilter()
# Exclude all methyl scans.
filter.exclude_torsion_scan(smarts="[*:1]~[*:2]-[CH3:3]-[H:4]")
# Only retain a limited ring scan
filter.include_torsion_scan(smarts="[*:1]~[*:2]:[*:3]~[*:4]") 
```
